name: security
description: Security package(login,register)
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

dependencies:
  core:
    path: "../core"
  database:
    path: "../database"
  freezed_annotation: ^2.2.0
  sqflite: ^2.2.7
